import {
  Type, Calculator, Wand2, Code, FileText, ArrowRightLeft,
  Binary, Hash, Link, Globe, Dices, Coins, Clock, Palette,
  Fingerprint, Thermometer, Scale, Ruler, Mail, Search, Zap,
  FileJson, Replace, Braces, Terminal, Image, FileImage, FileDown,
  LayoutTemplate, Link2, FileCode2, Smartphone, UploadCloud
} from 'lucide-react';
import { Tool } from './types';

export const tools: Tool[] = [
  // TEXT TOOLS (20)
  { id: 'word-count', title: 'Word Counter', seoTitle: 'Word Counter - Free Online Word Counter', seoDescription: 'Free online word counter. Count the number of words in your text directly in your browser. Fast, secure, and easy to use.', h1: 'Word Counter', intro: 'Welcome to our free online word counter. Count the number of words in your text.', description: 'Count the number of words in your text.', category: 'Text Tools', icon: FileText, type: 'text', action: (str: string) => str ? str.trim().split(/\s+/).length + " Words" : "0 Words" },
  { id: 'char-count', title: 'Character Counter', seoTitle: 'Character Counter - Free Online Character Counter', seoDescription: 'Free online character counter. Count characters with and without spaces directly in your browser. Fast, secure, and easy to use.', h1: 'Character Counter', intro: 'Welcome to our free online character counter. Count characters with and without spaces.', description: 'Count characters with and without spaces.', category: 'Text Tools', icon: Type, type: 'text', action: (str: string) => str ? str.length + " Characters" : "0 Characters" },
  { id: 'uppercase', title: 'Uppercase Converter', seoTitle: 'Uppercase Converter - Free Online Uppercase Converter', seoDescription: 'Free online uppercase converter. Convert your text to ALL CAPS directly in your browser. Fast, secure, and easy to use.', h1: 'Uppercase Converter', intro: 'Welcome to our free online uppercase converter. Convert your text to ALL CAPS.', description: 'Convert your text to ALL CAPS.', category: 'Text Tools', icon: Type, type: 'text', action: (str: string) => str.toUpperCase() },
  { id: 'lowercase', title: 'Lowercase Converter', seoTitle: 'Lowercase Converter - Free Online Lowercase Converter', seoDescription: 'Free online lowercase converter. Convert your text to lowercase directly in your browser. Fast, secure, and easy to use.', h1: 'Lowercase Converter', intro: 'Welcome to our free online lowercase converter. Convert your text to lowercase.', description: 'Convert your text to lowercase.', category: 'Text Tools', icon: Type, type: 'text', action: (str: string) => str.toLowerCase() },
  { id: 'title-case', title: 'Title Case', seoTitle: 'Title Case - Free Online Title Case', seoDescription: 'Free online title case. Capitalize the first letter of each word directly in your browser. Fast, secure, and easy to use.', h1: 'Title Case', intro: 'Welcome to our free online title case. Capitalize the first letter of each word.', description: 'Capitalize the first letter of each word.', category: 'Text Tools', icon: Type, type: 'text', action: (str: string) => str.replace(/\w\S*/g, txt => txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase()) },
  { id: 'reverse-text', title: 'Reverse Text', seoTitle: 'Reverse Text - Free Online Reverse Text', seoDescription: 'Free online reverse text. Reverse the characters in your text directly in your browser. Fast, secure, and easy to use.', h1: 'Reverse Text', intro: 'Welcome to our free online reverse text. Reverse the characters in your text.', description: 'Reverse the characters in your text.', category: 'Text Tools', icon: Replace, type: 'text', action: (str: string) => str.split('').reverse().join('') },
  { id: 'remove-spaces', title: 'Remove Extra Spaces', seoTitle: 'Remove Extra Spaces - Free Online Remove Extra Spaces', seoDescription: 'Free online remove extra spaces. Clean up text by removing multiple spaces directly in your browser. Fast, secure, and easy to use.', h1: 'Remove Extra Spaces', intro: 'Welcome to our free online remove extra spaces. Clean up text by removing multiple spaces.', description: 'Clean up text by removing multiple spaces.', category: 'Text Tools', icon: ArrowRightLeft, type: 'text', action: (str: string) => str.replace(/\s+/g, ' ').trim() },
  { id: 'slugify', title: 'URL Slug Generator', seoTitle: 'URL Slug Generator - Free Online URL Slug Generator', seoDescription: 'Free online url slug generator. Convert text into a URL-friendly slug directly in your browser. Fast, secure, and easy to use.', h1: 'URL Slug Generator', intro: 'Welcome to our free online url slug generator. Convert text into a URL-friendly slug.', description: 'Convert text into a URL-friendly slug.', category: 'Text Tools', icon: Link, type: 'text', action: (str: string) => str.toLowerCase().replace(/[^\w\s-]/g, '').replace(/[\s_-]+/g, '-').replace(/^-+|-+$/g, '') },
  { id: 'camel-case', title: 'Camel Case', seoTitle: 'Camel Case - Free Online Camel Case', seoDescription: 'Free online camel case. Convert text to camelCase Format directly in your browser. Fast, secure, and easy to use.', h1: 'Camel Case', intro: 'Welcome to our free online camel case. Convert text to camelCase Format.', description: 'Convert text to camelCase Format.', category: 'Text Tools', icon: Type, type: 'text', action: (str: string) => str.replace(/(?:^\w|[A-Z]|\b\w)/g, (w, i) => i === 0 ? w.toLowerCase() : w.toUpperCase()).replace(/\s+/g, '') },
  { id: 'snake-case', title: 'Snake Case', description: 'Convert text to snake_case format.', category: 'Text Tools', icon: Type, type: 'text', action: (str: string) => str.match(/[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|\b)|[A-Z]?[a-z]+[0-9]*|[A-Z]|[0-9]+/g)?.map(x => x.toLowerCase()).join('_') || '' },
  { id: 'kebab-case', title: 'Kebab Case', description: 'Convert text to kebab-case format.', category: 'Text Tools', icon: Type, type: 'text', action: (str: string) => str.match(/[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|\b)|[A-Z]?[a-z]+[0-9]*|[A-Z]|[0-9]+/g)?.map(x => x.toLowerCase()).join('-') || '' },
  { id: 'extract-emails', title: 'Email Extractor', seoTitle: 'Email Extractor - Free Online Email Extractor', seoDescription: 'Free online email extractor. Extract all email addresses from text directly in your browser. Fast, secure, and easy to use.', h1: 'Email Extractor', intro: 'Welcome to our free online email extractor. Extract all email addresses from text.', description: 'Extract all email addresses from text.', category: 'Text Tools', icon: Mail, type: 'text', action: (str: string) => str.match(/([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9._-]+)/gi)?.join('\n') || 'No emails found' },
  { id: 'extract-urls', title: 'URL Extractor', seoTitle: 'URL Extractor - Free Online URL Extractor', seoDescription: 'Free online url extractor. Extract all URLs from a block of text directly in your browser. Fast, secure, and easy to use.', h1: 'URL Extractor', intro: 'Welcome to our free online url extractor. Extract all URLs from a block of text.', description: 'Extract all URLs from a block of text.', category: 'Text Tools', icon: Globe, type: 'text', action: (str: string) => str.match(/(https?:\/\/[^\s]+)/g)?.join('\n') || 'No URLs found' },
  { id: 'vowel-counter', title: 'Vowel Counter', seoTitle: 'Vowel Counter - Free Online Vowel Counter', seoDescription: 'Free online vowel counter. Count the number of vowels in text directly in your browser. Fast, secure, and easy to use.', h1: 'Vowel Counter', intro: 'Welcome to our free online vowel counter. Count the number of vowels in text.', description: 'Count the number of vowels in text.', category: 'Text Tools', icon: Search, type: 'text', action: (str: string) => (str.match(/[aeiou]/gi) || []).length + " Vowels" },
  { id: 'consonant-counter', title: 'Consonant Counter', seoTitle: 'Consonant Counter - Free Online Consonant Counter', seoDescription: 'Free online consonant counter. Count the number of consonants directly in your browser. Fast, secure, and easy to use.', h1: 'Consonant Counter', intro: 'Welcome to our free online consonant counter. Count the number of consonants.', description: 'Count the number of consonants.', category: 'Text Tools', icon: Search, type: 'text', action: (str: string) => (str.match(/[bcdfghjklmnpqrstvwxyz]/gi) || []).length + " Consonants" },
  { id: 'palindrome-checker', title: 'Palindrome Checker', seoTitle: 'Palindrome Checker - Free Online Palindrome Checker', seoDescription: 'Free online palindrome checker. Check if text reads the same backwards directly in your browser. Fast, secure, and easy to use.', h1: 'Palindrome Checker', intro: 'Welcome to our free online palindrome checker. Check if text reads the same backwards.', description: 'Check if text reads the same backwards.', category: 'Text Tools', icon: Search, type: 'text', action: (str: string) => { const s = str.toLowerCase().replace(/[^a-z0-9]/g, ''); return (!s) ? "" : s === s.split('').reverse().join('') ? "Yes, it is a palindrome" : "No, it is not a palindrome"; } },
  { id: 'string-bytes', title: 'String to Bytes', seoTitle: 'String to Bytes - Free Online String to Bytes', seoDescription: 'Free online string to bytes. Calculate the byte size of a string directly in your browser. Fast, secure, and easy to use.', h1: 'String to Bytes', intro: 'Welcome to our free online string to bytes. Calculate the byte size of a string.', description: 'Calculate the byte size of a string.', category: 'Text Tools', icon: Binary, type: 'text', action: (str: string) => new Blob([str]).size + ' Bytes' },
  { id: 'line-counter', title: 'Line Counter', seoTitle: 'Line Counter - Free Online Line Counter', seoDescription: 'Free online line counter. Count the number of lines in text directly in your browser. Fast, secure, and easy to use.', h1: 'Line Counter', intro: 'Welcome to our free online line counter. Count the number of lines in text.', description: 'Count the number of lines in text.', category: 'Text Tools', icon: FileText, type: 'text', action: (str: string) => str ? str.split('\n').length + ' Lines' : '0 Lines' },
  { id: 'remove-newlines', title: 'Remove Line Breaks', seoTitle: 'Remove Line Breaks - Free Online Remove Line Breaks', seoDescription: 'Free online remove line breaks. Remove all line breaks from text directly in your browser. Fast, secure, and easy to use.', h1: 'Remove Line Breaks', intro: 'Welcome to our free online remove line breaks. Remove all line breaks from text.', description: 'Remove all line breaks from text.', category: 'Text Tools', icon: Replace, type: 'text', action: (str: string) => str.replace(/[\r\n]+/g, ' ') },
  { id: 'text-repeater', title: 'Text Repeater', seoTitle: 'Text Repeater - Free Online Text Repeater', seoDescription: 'Free online text repeater. Repeats text 5 times (for demo) directly in your browser. Fast, secure, and easy to use.', h1: 'Text Repeater', intro: 'Welcome to our free online text repeater. Repeats text 5 times (for demo).', description: 'Repeats text 5 times (for demo).', category: 'Text Tools', icon: Replace, type: 'text', action: (str: string) => Array(5).fill(str).join(' ') },

  // DEVELOPER TOOLS (10)
  { id: 'json-format', title: 'JSON Formatter', seoTitle: 'JSON Formatter - Free Online JSON Formatter', seoDescription: 'Free online json formatter. Beautify and format JSON strings directly in your browser. Fast, secure, and easy to use.', h1: 'JSON Formatter', intro: 'Welcome to our free online json formatter. Beautify and format JSON strings.', description: 'Beautify and format JSON strings.', category: 'Developer', icon: Braces, type: 'text', action: (str: string) => { if(!str) return ''; try { return JSON.stringify(JSON.parse(str), null, 2); } catch(e) { return "Invalid JSON"; } } },
  { id: 'json-minify', title: 'JSON Minifier', seoTitle: 'JSON Minifier - Free Online JSON Minifier', seoDescription: 'Free online json minifier. Compress JSON strings by removing spaces directly in your browser. Fast, secure, and easy to use.', h1: 'JSON Minifier', intro: 'Welcome to our free online json minifier. Compress JSON strings by removing spaces.', description: 'Compress JSON strings by removing spaces.', category: 'Developer', icon: FileJson, type: 'text', action: (str: string) => { if(!str) return ''; try { return JSON.stringify(JSON.parse(str)); } catch(e) { return "Invalid JSON"; } } },
  { id: 'html-encode', title: 'HTML Encode', seoTitle: 'HTML Encode - Free Online HTML Encode', seoDescription: 'Free online html encode. Convert characters to HTML entities directly in your browser. Fast, secure, and easy to use.', h1: 'HTML Encode', intro: 'Welcome to our free online html encode. Convert characters to HTML entities.', description: 'Convert characters to HTML entities.', category: 'Developer', icon: Code, type: 'text', action: (str: string) => str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') },
  { id: 'html-decode', title: 'HTML Decode', seoTitle: 'HTML Decode - Free Online HTML Decode', seoDescription: 'Free online html decode. Decode HTML entities back to characters directly in your browser. Fast, secure, and easy to use.', h1: 'HTML Decode', intro: 'Welcome to our free online html decode. Decode HTML entities back to characters.', description: 'Decode HTML entities back to characters.', category: 'Developer', icon: Terminal, type: 'text', action: (str: string) => { const doc = new DOMParser().parseFromString(str, "text/html"); return doc.documentElement.textContent || ''; } },
  { id: 'base64-encode', title: 'Base64 Encode', seoTitle: 'Base64 Encode - Free Online Base64 Encode', seoDescription: 'Free online base64 encode. Encode string to Base64 format directly in your browser. Fast, secure, and easy to use.', h1: 'Base64 Encode', intro: 'Welcome to our free online base64 encode. Encode string to Base64 format.', description: 'Encode string to Base64 format.', category: 'Developer', icon: Hash, type: 'text', action: (str: string) => { try { return btoa(unescape(encodeURIComponent(str))); } catch(e) { return 'Error'; } } },
  { id: 'base64-decode', title: 'Base64 Decode', seoTitle: 'Base64 Decode - Free Online Base64 Decode', seoDescription: 'Free online base64 decode. Decode Base64 string to normal text directly in your browser. Fast, secure, and easy to use.', h1: 'Base64 Decode', intro: 'Welcome to our free online base64 decode. Decode Base64 string to normal text.', description: 'Decode Base64 string to normal text.', category: 'Developer', icon: Hash, type: 'text', action: (str: string) => { try { return decodeURIComponent(escape(atob(str))); } catch(e) { return 'Invalid Base64'; } } },
  { id: 'url-encode', title: 'URL Encode', seoTitle: 'URL Encode - Free Online URL Encode', seoDescription: 'Free online url encode. Encode a string for use in URLs directly in your browser. Fast, secure, and easy to use.', h1: 'URL Encode', intro: 'Welcome to our free online url encode. Encode a string for use in URLs.', description: 'Encode a string for use in URLs.', category: 'Developer', icon: Link, type: 'text', action: (str: string) => encodeURIComponent(str) },
  { id: 'url-decode', title: 'URL Decode', seoTitle: 'URL Decode - Free Online URL Decode', seoDescription: 'Free online url decode. Decode a URL-encoded string directly in your browser. Fast, secure, and easy to use.', h1: 'URL Decode', intro: 'Welcome to our free online url decode. Decode a URL-encoded string.', description: 'Decode a URL-encoded string.', category: 'Developer', icon: Link, type: 'text', action: (str: string) => { try { return decodeURIComponent(str); } catch(e) { return 'Invalid URL encoding'; } } },
  { id: 'binary-encode', title: 'Text to Binary', seoTitle: 'Text to Binary - Free Online Text to Binary', seoDescription: 'Free online text to binary. Convert text characters to binary directly in your browser. Fast, secure, and easy to use.', h1: 'Text to Binary', intro: 'Welcome to our free online text to binary. Convert text characters to binary.', description: 'Convert text characters to binary.', category: 'Developer', icon: Binary, type: 'text', action: (str: string) => str.split('').map(char => char.charCodeAt(0).toString(2).padStart(8, '0')).join(' ') },
  { id: 'binary-decode', title: 'Binary to Text', seoTitle: 'Binary to Text - Free Online Binary to Text', seoDescription: 'Free online binary to text. Convert binary code back to text directly in your browser. Fast, secure, and easy to use.', h1: 'Binary to Text', intro: 'Welcome to our free online binary to text. Convert binary code back to text.', description: 'Convert binary code back to text.', category: 'Developer', icon: Binary, type: 'text', action: (str: string) => str.split(' ').map(bin => String.fromCharCode(parseInt(bin, 2) || 0)).join('') },

  // GENERATORS (10)
  { id: 'uuid-v4', title: 'UUID v4 Generator', seoTitle: 'UUID v4 Generator - Free Online UUID v4 Generator', seoDescription: 'Free online uuid v4 generator. Generate a random UUID version 4 directly in your browser. Fast, secure, and easy to use.', h1: 'UUID v4 Generator', intro: 'Welcome to our free online uuid v4 generator. Generate a random UUID version 4.', description: 'Generate a random UUID version 4.', category: 'Generators', icon: Fingerprint, type: 'generator', action: () => crypto.randomUUID() },
  { id: 'password-gen', title: 'Password Generator', seoTitle: 'Password Generator - Free Online Password Generator', seoDescription: 'Free online password generator. Generate a strong 16-character password directly in your browser. Fast, secure, and easy to use.', h1: 'Password Generator', intro: 'Welcome to our free online password generator. Generate a strong 16-character password.', description: 'Generate a strong 16-character password.', category: 'Generators', icon: Hash, type: 'generator', action: () => Array.from(crypto.getRandomValues(new Uint32Array(16))).map(x => x.toString(36)).join('').slice(0, 16) },
  { id: 'random-number', title: 'Random Number (1-100)', seoTitle: 'Random Number (1-100) - Free Online Random Number (1-100)', seoDescription: 'Free online random number (1-100). Generate a random number between 1 and 100 directly in your browser. Fast, secure, and easy to use.', h1: 'Random Number (1-100)', intro: 'Welcome to our free online random number (1-100). Generate a random number between 1 and 100.', description: 'Generate a random number between 1 and 100.', category: 'Generators', icon: Dices, type: 'generator', action: () => Math.floor(Math.random() * 100) + 1 },
  { id: 'coin-flip', title: 'Coin Flipper', seoTitle: 'Coin Flipper - Free Online Coin Flipper', seoDescription: 'Free online coin flipper. Simulate a coin flip (Heads/Tails) directly in your browser. Fast, secure, and easy to use.', h1: 'Coin Flipper', intro: 'Welcome to our free online coin flipper. Simulate a coin flip (Heads/Tails).', description: 'Simulate a coin flip (Heads/Tails).', category: 'Generators', icon: Coins, type: 'generator', action: () => Math.random() > 0.5 ? 'Heads' : 'Tails' },
  { id: 'dice-roll', title: 'Dice Roller', seoTitle: 'Dice Roller - Free Online Dice Roller', seoDescription: 'Free online dice roller. Roll a virtual 6-sided die directly in your browser. Fast, secure, and easy to use.', h1: 'Dice Roller', intro: 'Welcome to our free online dice roller. Roll a virtual 6-sided die.', description: 'Roll a virtual 6-sided die.', category: 'Generators', icon: Dices, type: 'generator', action: () => Math.floor(Math.random() * 6) + 1 },
  { id: 'random-hex', title: 'Random HEX Color', seoTitle: 'Random HEX Color - Free Online Random HEX Color', seoDescription: 'Free online random hex color. Generate a random HEX color code directly in your browser. Fast, secure, and easy to use.', h1: 'Random HEX Color', intro: 'Welcome to our free online random hex color. Generate a random HEX color code.', description: 'Generate a random HEX color code.', category: 'Generators', icon: Palette, type: 'generator', action: () => '#' + Math.floor(Math.random()*16777215).toString(16).padStart(6, '0') },
  { id: 'random-rgb', title: 'Random RGB Color', description: 'Generate a random RGB color code.', category: 'Generators', icon: Palette, type: 'generator', action: () => `rgb(${Math.floor(Math.random()*256)}, ${Math.floor(Math.random()*256)}, ${Math.floor(Math.random()*256)})` },
  { id: 'mac-address', title: 'MAC Address Generator', seoTitle: 'MAC Address Generator - Free Online MAC Address Generator', seoDescription: 'Free online mac address generator. Generate a random MAC address directly in your browser. Fast, secure, and easy to use.', h1: 'MAC Address Generator', intro: 'Welcome to our free online mac address generator. Generate a random MAC address.', description: 'Generate a random MAC address.', category: 'Generators', icon: Globe, type: 'generator', action: () => "XX:XX:XX:XX:XX:XX".replace(/X/g, () => "0123456789ABCDEF".charAt(Math.floor(Math.random() * 16))) },
  { id: 'ipv4-gen', title: 'IPv4 Generator', description: 'Generate a random IPv4 address.', category: 'Generators', icon: Globe, type: 'generator', action: () => Array.from({length: 4}, () => Math.floor(Math.random() * 256)).join('.') },
  { id: 'timestamp-now', title: 'Current Timestamp', seoTitle: 'Current Timestamp - Free Online Current Timestamp', seoDescription: 'Free online current timestamp. Get the current UNIX timestamp directly in your browser. Fast, secure, and easy to use.', h1: 'Current Timestamp', intro: 'Welcome to our free online current timestamp. Get the current UNIX timestamp.', description: 'Get the current UNIX timestamp.', category: 'Generators', icon: Clock, type: 'generator', action: () => Date.now().toString() },

  // CALCULATORS (10)
  { id: 'tip-calculator', title: 'Tip Calculator', description: 'Calculate tip amount easily.', category: 'Calculators', icon: Calculator, type: 'calculator', inputs: [{name: 'amount', label: 'Bill Amount ($)'}, {name: 'tip', label: 'Tip Percentage (%)'}], action: (amount, tip) => `Total Bill: $${(amount * (1 + tip/100)).toFixed(2)}` },
  { id: 'discount-calc', title: 'Discount Calculator', description: 'Calculate final price after discount.', category: 'Calculators', icon: Calculator, type: 'calculator', inputs: [{name: 'price', label: 'Original Price ($)'}, {name: 'discount', label: 'Discount (%)'}], action: (price, discount) => `Final Price: $${(price * (1 - discount/100)).toFixed(2)}` },
  { id: 'bmi-calc', title: 'BMI Calculator', description: 'Calculate Body Mass Index (BMI).', category: 'Calculators', icon: Scale, type: 'calculator', inputs: [{name: 'weight', label: 'Weight (kg)'}, {name: 'height', label: 'Height (cm)'}], action: (w, h) => h > 0 ? `Your BMI: ${(w / Math.pow(h/100, 2)).toFixed(1)}` : '0' },
  { id: 'age-calc', title: 'Age Calculator', description: 'Calculate age from birth year.', category: 'Calculators', icon: Clock, type: 'calculator', inputs: [{name: 'year', label: 'Birth Year'}], action: (year) => year > 0 ? `Age: ${new Date().getFullYear() - year} Years` : '0 Years' },
  { id: 'markup-calc', title: 'Markup Calculator', description: 'Calculate price based on cost & markup %.', category: 'Calculators', icon: Calculator, type: 'calculator', inputs: [{name: 'cost', label: 'Cost Price'}, {name: 'markup', label: 'Markup (%)'}], action: (cost, markup) => `Selling Price: ${(cost * (1 + markup/100)).toFixed(2)}` },
  { id: 'profit-margin', title: 'Profit Margin Calculator', description: 'Calculate margin from cost and revenue.', category: 'Calculators', icon: Calculator, type: 'calculator', inputs: [{name: 'cost', label: 'Cost'}, {name: 'revenue', label: 'Revenue'}], action: (cost, revenue) => revenue > 0 ? `Margin: ${(((revenue - cost) / revenue) * 100).toFixed(2)}%` : '0%' },
  { id: 'loan-interest', title: 'Simple Interest', description: 'Calculate simple interest on a loan.', category: 'Calculators', icon: Calculator, type: 'calculator', inputs: [{name: 'principal', label: 'Principal'}, {name: 'rate', label: 'Rate (%)'}, {name: 'years', label: 'Years'}], action: (p, r, y) => `Interest: ${((p * r * y) / 100).toFixed(2)}` },
  { id: 'celsius-to-fahrenheit', title: 'Celsius to Fahrenheit', description: 'Convert temp from Celsius to Fahrenheit.', category: 'Converters', icon: Thermometer, type: 'calculator', inputs: [{name: 'c', label: 'Celsius (°C)'}], action: (c) => `${(c * 9/5 + 32).toFixed(2)} °F` },
  { id: 'fahrenheit-to-celsius', title: 'Fahrenheit to Celsius', description: 'Convert temp from Fahrenheit to Celsius.', category: 'Converters', icon: Thermometer, type: 'calculator', inputs: [{name: 'f', label: 'Fahrenheit (°F)'}], action: (f) => `${((f - 32) * 5/9).toFixed(2)} °C` },
  { id: 'km-to-miles', title: 'KM to Miles Converter', description: 'Convert kilometers to miles.', category: 'Converters', icon: Ruler, type: 'calculator', inputs: [{name: 'km', label: 'Kilometers (km)'}], action: (km) => `${(km * 0.621371).toFixed(2)} Miles` },
  
  // MEDIA & DOCUMENT TOOLS
  { id: 'image-hosting', title: 'Image Hosting (ImgBB)', seoTitle: 'Image Hosting (ImgBB) - Free Online Image Hosting (ImgBB)', seoDescription: 'Free online image hosting (imgbb). Upload and host your images instantly using ImgBB directly in your browser. Fast, secure, and easy to use.', h1: 'Image Hosting (ImgBB)', intro: 'Welcome to our free online image hosting (imgbb). Upload and host your images instantly using ImgBB.', description: 'Upload and host your images instantly using ImgBB.', category: 'Media Tools', icon: UploadCloud, type: 'image_hosting', action: () => '' },
  { id: 'image-compressor', title: 'Image Compressor', seoTitle: 'Image Compressor - Free Online Image Compressor', seoDescription: 'Free online image compressor. Compress images online without losing quality directly in your browser. Fast, secure, and easy to use.', h1: 'Image Compressor', intro: 'Welcome to our free online image compressor. Compress images online without losing quality.', description: 'Compress images online without losing quality.', category: 'Media Tools', icon: Image, type: 'image_compressor', action: () => '' },
  { id: 'image-converter', title: 'Image Converter', seoTitle: 'Image Converter - Free Online Image Converter', seoDescription: 'Free online image converter. Convert images to PNG, JPG, or WEBP formats directly in your browser. Fast, secure, and easy to use.', h1: 'Image Converter', intro: 'Welcome to our free online image converter. Convert images to PNG, JPG, or WEBP formats.', description: 'Convert images to PNG, JPG, or WEBP formats.', category: 'Media Tools', icon: FileImage, type: 'image_converter', action: () => '' },
  { id: 'text-to-pdf', title: 'Text to PDF', seoTitle: 'Text to PDF - Free Online Text to PDF', seoDescription: 'Free online text to pdf. Convert plain text directly into a PDF document directly in your browser. Fast, secure, and easy to use.', h1: 'Text to PDF', intro: 'Welcome to our free online text to pdf. Convert plain text directly into a PDF document.', description: 'Convert plain text directly into a PDF document.', category: 'Document Tools', icon: FileDown, type: 'text_to_pdf', action: () => '' },
  { id: 'text-to-file', title: 'Text to File', seoTitle: 'Text to File - Free Online Text to File', seoDescription: 'Free online text to file. Convert your text into HTML, CSS, JS, or TXT files instantly directly in your browser. Fast, secure, and easy to use.', h1: 'Text to File', intro: 'Welcome to our free online text to file. Convert your text into HTML, CSS, JS, or TXT files instantly.', description: 'Convert your text into HTML, CSS, JS, or TXT files instantly.', category: 'Document Tools', icon: FileCode2, type: 'text_to_file', action: () => '' },
  
  // WEB TOOLS
  { id: 'html-viewer', title: 'HTML Viewer', seoTitle: 'HTML Viewer - Free Online HTML Viewer', seoDescription: 'Free online html viewer. Live preview your HTML/CSS code instantly in the browser directly in your browser. Fast, secure, and easy to use.', h1: 'HTML Viewer', intro: 'Welcome to our free online html viewer. Live preview your HTML/CSS code instantly in the browser.', description: 'Live preview your HTML/CSS code instantly in the browser.', category: 'Web Tools', icon: LayoutTemplate, type: 'html_viewer', action: () => '' },
  { id: 'url-shortener', title: 'URL Shortener', seoTitle: 'URL Shortener - Free Online URL Shortener', seoDescription: 'Free online url shortener. Shorten long URLs into tiny, easily shareable links directly in your browser. Fast, secure, and easy to use.', h1: 'URL Shortener', intro: 'Welcome to our free online url shortener. Shorten long URLs into tiny, easily shareable links.', description: 'Shorten long URLs into tiny, easily shareable links.', category: 'Web Tools', icon: Link2, type: 'url_shortener', action: () => '' },
  { id: 'pwa-generator', title: 'PWA / App Generator', seoTitle: 'PWA / App Generator - Free Online PWA / App Generator', seoDescription: 'Free online pwa / app generator. Convert your HTML/JS site into an installable Mobile App (PWA) directly in your browser. Fast, secure, and easy to use.', h1: 'PWA / App Generator', intro: 'Welcome to our free online pwa / app generator. Convert your HTML/JS site into an installable Mobile App (PWA).', description: 'Convert your HTML/JS site into an installable Mobile App (PWA).', category: 'Web Tools', icon: Smartphone, type: 'pwa_generator', action: () => '' },
  { id: 'web-to-app', title: 'Web to App (Android)', seoTitle: 'Web to App (Android) - Free Online Web to App (Android)', seoDescription: 'Free online web to app (android). Convert any website URL into an Android Studio WebView project directly in your browser. Fast, secure, and easy to use.', h1: 'Web to App (Android)', intro: 'Welcome to our free online web to app (android). Convert any website URL into an Android Studio WebView project.', description: 'Convert any website URL into an Android Studio WebView project.', category: 'Web Tools', icon: Globe, type: 'web_to_app', action: () => '' }
];
